language: node_js
node_js:
  - "8"
script:
  - npm run test
  - npm run build
branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+$/
deploy:
  provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_TOKEN"
  skip_cleanup: true
  on:
    tags: true
  tag: latest

notifications:
  email: false
